# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiQC8CH0KzH9HyZFMLN688H3w6tGfaIM
"""

pip install streamlit openai

import streamlit as st
import openai

# Streamlit 앱 제목 설정
st.title("OpenAI Assistant 챗봇")

# OpenAI API Key 입력 받기
openai_api_key = st.text_input("OpenAI API Key를 입력하세요:", type="password")

# Assistant ID 설정 (asst_y81y2F3Ea7fGynY1tiTxIjPX)
assistant_id = "asst_y81y2F3Ea7fGynY1tiTxIjPX"

# 채팅 기록 초기화
if "messages" not in st.session_state:
    st.session_state.messages = []

# 사용자 메시지 입력 받기
user_input = st.text_input("메시지를 입력하세요:")

# 메시지 전송 버튼 클릭 시
if st.button("전송"):
    # OpenAI API Key 설정
    openai.api_key = openai_api_key

    # 사용자 메시지를 채팅 기록에 추가
    st.session_state.messages.append({"role": "user", "content": user_input})

    # OpenAI Assistant API 호출
    response = openai.beta.assistants.create_run(
        assistant_id=assistant_id,
        instructions="You are a helpful and informative assistant.",
        tools=[],
        model="gpt-4-1105-preview",
        thread={
            "messages": st.session_state.messages,
        },
    )

    # Assistant 응답 대기
    response = openai.beta.assistants.retrieve_run(
        assistant_id=assistant_id,
        run_id=response.id,
    )

    while response.status == 'in_progress':
      response = openai.beta.assistants.retrieve_run(
          assistant_id=assistant_id,
          run_id=response.id,
      )

    # Assistant 응답을 채팅 기록에 추가
    st.session_state.messages.extend(response.thread.messages[1:])

# 채팅 기록 표시
for message in st.session_state.messages:
    if message["role"] == "user":
        st.write(f"**사용자:** {message['content']}")
    elif message["role"] == "assistant":
        st.write(f"**Assistant:** {message['content']}")